{
 "title": "Sensors",
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "All sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  \"timestamp\", \r\n  CASE \r\n    WHEN \"sensor_id\" = 'sensor1' THEN \"value\"\r\n    ELSE NULL\r\n  END AS \"sensor1\",\r\n  CASE \r\n    WHEN \"sensor_id\" = 'sensor2' THEN \"value\"\r\n    ELSE NULL\r\n  END AS \"sensor2\",\r\n  CASE \r\n    WHEN \"sensor_id\" = 'sensor3' THEN \"value\"\r\n    ELSE NULL\r\n  END AS \"sensor3\"\r\nFROM \"sensor_data\"\r\nWHERE \"sensor_id\" IN ('sensor1', 'sensor2', 'sensor3')\r\nORDER BY \"timestamp\" DESC\r\nLIMIT 300"
    }
   ]
  },
  {
   "title": "Sensor1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value\r\nFROM sensor_data\r\nWHERE sensor_id = 'sensor1'\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Sensor2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value\r\nFROM sensor_data\r\nWHERE sensor_id = 'sensor2'\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Sensor3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value\r\nFROM sensor_data\r\nWHERE sensor_id = 'sensor3'\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp;"
    }
   ]
  }
 ]
}